name: 'publish-docs'
description: 'Publish docs with nbdev to netlify'
inputs:
  NETLIFY_AUTH_TOKEN:
    description: Auth token to use with netlify
    required: true
    default: ""
  python_version:
    description: 'Version of python to set up'
    required: false
    default: "3.12"
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: "pip"
        cache-dependency-path: settings.ini
    - name: Install Dependencies
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -Uq nbdev
        nbdev_proc_nbs
        cp _quarto.yml ./_proc/_quarto.yml
    
    - name: Render and Publish 
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        path: _proc
        target: netlify
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}